/*
 * Copyright 2023 ICE9 Consulting LLC
 */

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

typedef enum VkFFTResult {
    VKFFT_SUCCESS = 0,
    VKFFT_ERROR_MALLOC_FAILED = 1,
    VKFFT_ERROR_INSUFFICIENT_CODE_BUFFER = 2,
    VKFFT_ERROR_INSUFFICIENT_TEMP_BUFFER = 3,
    VKFFT_ERROR_PLAN_NOT_INITIALIZED = 4,
    VKFFT_ERROR_NULL_TEMP_PASSED = 5,
    VKFFT_ERROR_INVALID_PHYSICAL_DEVICE = 1001,
    VKFFT_ERROR_INVALID_DEVICE = 1002,
    VKFFT_ERROR_INVALID_QUEUE = 1003,
    VKFFT_ERROR_INVALID_COMMAND_POOL = 1004,
    VKFFT_ERROR_INVALID_FENCE = 1005,
    VKFFT_ERROR_ONLY_FORWARD_FFT_INITIALIZED = 1006,
    VKFFT_ERROR_ONLY_INVERSE_FFT_INITIALIZED = 1007,
    VKFFT_ERROR_INVALID_CONTEXT = 1008,
    VKFFT_ERROR_INVALID_PLATFORM = 1009,
    VKFFT_ERROR_ENABLED_saveApplicationToString = 1010,
    VKFFT_ERROR_EMPTY_FILE = 1011,
    VKFFT_ERROR_EMPTY_FFTdim = 2001,
    VKFFT_ERROR_EMPTY_size = 2002,
    VKFFT_ERROR_EMPTY_bufferSize = 2003,
    VKFFT_ERROR_EMPTY_buffer = 2004,
    VKFFT_ERROR_EMPTY_tempBufferSize = 2005,
    VKFFT_ERROR_EMPTY_tempBuffer = 2006,
    VKFFT_ERROR_EMPTY_inputBufferSize = 2007,
    VKFFT_ERROR_EMPTY_inputBuffer = 2008,
    VKFFT_ERROR_EMPTY_outputBufferSize = 2009,
    VKFFT_ERROR_EMPTY_outputBuffer = 2010,
    VKFFT_ERROR_EMPTY_kernelSize = 2011,
    VKFFT_ERROR_EMPTY_kernel = 2012,
    VKFFT_ERROR_EMPTY_applicationString = 2013,
    VKFFT_ERROR_EMPTY_useCustomBluesteinPaddingPattern_arrays = 2014,
    VKFFT_ERROR_UNSUPPORTED_RADIX = 3001,
    VKFFT_ERROR_UNSUPPORTED_FFT_LENGTH = 3002,
    VKFFT_ERROR_UNSUPPORTED_FFT_LENGTH_R2C = 3003,
    VKFFT_ERROR_UNSUPPORTED_FFT_LENGTH_DCT = 3004,
    VKFFT_ERROR_UNSUPPORTED_FFT_OMIT = 3005,
    VKFFT_ERROR_FAILED_TO_ALLOCATE = 4001,
    VKFFT_ERROR_FAILED_TO_MAP_MEMORY = 4002,
    VKFFT_ERROR_FAILED_TO_ALLOCATE_COMMAND_BUFFERS = 4003,
    VKFFT_ERROR_FAILED_TO_BEGIN_COMMAND_BUFFER = 4004,
    VKFFT_ERROR_FAILED_TO_END_COMMAND_BUFFER = 4005,
    VKFFT_ERROR_FAILED_TO_SUBMIT_QUEUE = 4006,
    VKFFT_ERROR_FAILED_TO_WAIT_FOR_FENCES = 4007,
    VKFFT_ERROR_FAILED_TO_RESET_FENCES = 4008,
    VKFFT_ERROR_FAILED_TO_CREATE_DESCRIPTOR_POOL = 4009,
    VKFFT_ERROR_FAILED_TO_CREATE_DESCRIPTOR_SET_LAYOUT = 4010,
    VKFFT_ERROR_FAILED_TO_ALLOCATE_DESCRIPTOR_SETS = 4011,
    VKFFT_ERROR_FAILED_TO_CREATE_PIPELINE_LAYOUT = 4012,
    VKFFT_ERROR_FAILED_SHADER_PREPROCESS = 4013,
    VKFFT_ERROR_FAILED_SHADER_PARSE = 4014,
    VKFFT_ERROR_FAILED_SHADER_LINK = 4015,
    VKFFT_ERROR_FAILED_SPIRV_GENERATE = 4016,
    VKFFT_ERROR_FAILED_TO_CREATE_SHADER_MODULE = 4017,
    VKFFT_ERROR_FAILED_TO_CREATE_INSTANCE = 4018,
    VKFFT_ERROR_FAILED_TO_SETUP_DEBUG_MESSENGER = 4019,
    VKFFT_ERROR_FAILED_TO_FIND_PHYSICAL_DEVICE = 4020,
    VKFFT_ERROR_FAILED_TO_CREATE_DEVICE = 4021,
    VKFFT_ERROR_FAILED_TO_CREATE_FENCE = 4022,
    VKFFT_ERROR_FAILED_TO_CREATE_COMMAND_POOL = 4023,
    VKFFT_ERROR_FAILED_TO_CREATE_BUFFER = 4024,
    VKFFT_ERROR_FAILED_TO_ALLOCATE_MEMORY = 4025,
    VKFFT_ERROR_FAILED_TO_BIND_BUFFER_MEMORY = 4026,
    VKFFT_ERROR_FAILED_TO_FIND_MEMORY = 4027,
    VKFFT_ERROR_FAILED_TO_SYNCHRONIZE = 4028,
    VKFFT_ERROR_FAILED_TO_COPY = 4029,
    VKFFT_ERROR_FAILED_TO_CREATE_PROGRAM = 4030,
    VKFFT_ERROR_FAILED_TO_COMPILE_PROGRAM = 4031,
    VKFFT_ERROR_FAILED_TO_GET_CODE_SIZE = 4032,
    VKFFT_ERROR_FAILED_TO_GET_CODE = 4033,
    VKFFT_ERROR_FAILED_TO_DESTROY_PROGRAM = 4034,
    VKFFT_ERROR_FAILED_TO_LOAD_MODULE = 4035,
    VKFFT_ERROR_FAILED_TO_GET_FUNCTION = 4036,
    VKFFT_ERROR_FAILED_TO_SET_DYNAMIC_SHARED_MEMORY = 4037,
    VKFFT_ERROR_FAILED_TO_MODULE_GET_GLOBAL = 4038,
    VKFFT_ERROR_FAILED_TO_LAUNCH_KERNEL = 4039,
    VKFFT_ERROR_FAILED_TO_EVENT_RECORD = 4040,
    VKFFT_ERROR_FAILED_TO_ADD_NAME_EXPRESSION = 4041,
    VKFFT_ERROR_FAILED_TO_INITIALIZE = 4042,
    VKFFT_ERROR_FAILED_TO_SET_DEVICE_ID = 4043,
    VKFFT_ERROR_FAILED_TO_GET_DEVICE = 4044,
    VKFFT_ERROR_FAILED_TO_CREATE_CONTEXT = 4045,
    VKFFT_ERROR_FAILED_TO_CREATE_PIPELINE = 4046,
    VKFFT_ERROR_FAILED_TO_SET_KERNEL_ARG = 4047,
    VKFFT_ERROR_FAILED_TO_CREATE_COMMAND_QUEUE = 4048,
    VKFFT_ERROR_FAILED_TO_RELEASE_COMMAND_QUEUE = 4049,
    VKFFT_ERROR_FAILED_TO_ENUMERATE_DEVICES = 4050,
    VKFFT_ERROR_FAILED_TO_GET_ATTRIBUTE = 4051,
    VKFFT_ERROR_FAILED_TO_CREATE_EVENT = 4052,
    VKFFT_ERROR_FAILED_TO_CREATE_COMMAND_LIST = 4053,
    VKFFT_ERROR_FAILED_TO_DESTROY_COMMAND_LIST = 4054,
    VKFFT_ERROR_FAILED_TO_SUBMIT_BARRIER = 4055
} VkFFTResult;


VkFFTResult init_vkfft(unsigned width, unsigned batch_size);
void deinit_vkfft(void);
void release_buffer(void *buf_in);

void *get_next_buffer(void);

#ifdef __cplusplus
}
#endif
